---
title: "第11回講義コード解説"
subtitle: "2025年度 神戸大学経済学部・経済統計学"
date: today
date-format: "YYYY年M月D日"
author:
  - name: "Hirotaka Fukui"
    email: "227e127e@gsuite.kobe-u.ac.jp"
    affiliations:
      - name: "Kobe University, Graduate School of Economics"

format:
  typst:
    theme: default
    mainfont: "Noto Serif JP"
    sansfont: "IBM Plex Sans JP"
    number-sections: true
execute:
  echo: true          
jupyter: nbstata      
brand:
  typography:
    fonts:
      - family: "Noto Serif JP"
        source: google
      - family: "IBM Plex Sans JP"
        source: google
    base: "Noto Serif JP"
    headings:
      family: "IBM Plex Sans JP"
      weight: regular
---

# DiDの推定(練習問題)

藪先生の教科書p311の例14-2: 「差の差分析によって最低賃金引き上げの効果を見る」を再現してみましょう。

## データのインポート
```{stata}
clear all
set more off

import delimited 11-2.csv, clear
```

### データ内容

[Card, David and Alan B. Krueger. 1994. Minimum Wages and Employment: A Case Study of the Fast-Food Industry in New Jersey and Pennsylvania, American Economic Review 84(4): 772-793.](https://www.jstor.org/stable/2118030)

業種：ファストフード店

地域：

- ニュージャージー州（NJ）＝ 最低賃金を引き上げた州
- ペンシルベニア州（PA）＝引き上げなかった州

時点：

- 政策前（最低賃金引き上げ前）
- 政策後（引き上げ後）

変数
- store: 店舗ID
- state: 店舗iがニュージャージー(NJ)州に立地しているなら1をとるダミー変数。
- time: 処置後の11月の調査ならば1をとるダミー変数。 
- fulltime: フルタイム換算の雇用者数
- hours: 営業時間
- register: レジの台数

研究テーマ: 「最低賃金引上げは雇用を減らすのか、減らさないのか？」

Card & Krueger (1994) は、David Card が[ノーベル経済学賞（2021年）](https://www.nobelprize.org/prizes/economic-sciences/2021/summary/)を受賞した理由を代表する研究の一つです。

Cardは、共著者のKruegerとともに、1992年にアメリカで行われた最低賃金の引き上げが雇用にどのような影響を与えたのかを調べました。1992年4月1日、ニュージャージー州では最低賃金が引き上げられましたが、隣のペンシルバニア州では同じ時期に最低賃金の変更がありませんでした。CardとKruegerは、この違いを利用して、最低賃金の影響を調べることができると考えました。

彼らは、ニュージャージー州とペンシルバニア州の州境付近にある、同じような立地条件のファストフード店を調査対象に選びました。そして、最低賃金が引き上げられる前と後で、それぞれの店舗の従業員数がどのように変化したのかを比較しました。

その結果、最低賃金が引き上げられなかったペンシルバニア州では雇用が減っていたのに対し、最低賃金が引き上げられたニュージャージー州では、雇用がわずかに増えていることがわかりました。この結果から、彼らは「最低賃金を引き上げると、必ず雇用が減るとは限らない」と主張しました。

通説

- 最低賃金の引き上げにより雇用は減る（競争的労働市場モデル）

**Card & Krueger (1994)の結論**

- ニュージャージー州の最低賃金引き上げにより雇用は減らなかった（むしろ増えた可能性）

労働市場の競争仮定に疑問を突きつけた

詳しい解説はこの分野の専門家である川口大司先生によって書かれた

[『社会問題の因果関係を解明する「自然実験」の確立：ノーベル経済学賞2021』](https://www.crepe.e.u-tokyo.ac.jp/material/crepecl13.html)

を参照。

> The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel 2021 was divided, one half awarded to David Card "for his empirical contributions to labour economics", the other half jointly to Joshua D. Angrist and Guido W. Imbens "for their methodological contributions to the analysis of causal relationships"

> 2021年のアルフレッド・ノーベル記念スウェーデン国立銀行経済学賞は2つに分けて授与され、その半分が David Card に「労働経済学における実証的貢献」を理由として、残りの半分が Joshua D. Angrist と Guido W. Imbens に「因果関係の分析に関する方法論的貢献」を理由として共同で授与されました。

2021年ノーベル経済学賞に関する平易な解説: [Popular information. NobelPrize.org. Nobel Prize Outreach 2026. Tue. 6 Jan 2026.](https://www.nobelprize.org/prizes/economic-sciences/2021/popular-information/)

2021年ノーベル経済学賞に関する専門的な解説: [Advanced information. NobelPrize.org. Nobel Prize Outreach 2026. Tue. 6 Jan 2026.](https://www.nobelprize.org/prizes/economic-sciences/2021/advanced-information/)

#### 練習問題1: 今回の分析における処置群と対照群はそれぞれ何になりますか?
#### 練習問題2: 2期間のシンプルな時間構造において各グループ、各期のfulltimeへの効果を講義資料 「Ⅱ　DiD分析の枠組み」のStep2のように表にまとめてみましょう。
#### 練習問題3: その状況をStep3のように絵にしてみましょう。
#### 練習問題4: その絵をもとに求めるべき政策効果の大きさを整理し、導出してみましょう。

## パネルデータの作成

```{stata}

xtset store time
```

## 交差項の作成

```{stata}
gen timestate = time*state
```

## 各state×timeでfulltime平均値の比較

```{stata}
mean fulltime if (state==1 & time==0)  // NJ, before
mean fulltime if (state==1 & time==1)  // NJ, after
mean fulltime if (state==0 & time==0)  // PA, before
mean fulltime if (state==0 & time==1)  // PA, after
```

- $\mu_{10}$ = State=1, time=0: ニュージャージー州に店舗が立地していてなおかつ処置前
- $\mu_{11}$ = State=1, time=1: ニュージャージー州に店舗が立地していてなおかつ処置後
- $\mu_{00}$ = State=0, time=0: ペンシルバニア州に店舗が立地していてなおかつ処置前
- $\mu_{01}$ = State=0, time=1: ペンシルバニア州に店舗が立地していてなおかつ処置後

### 練習問題5: ニュージャージー州による最低賃金引き上げの政策効果はそれぞれの場合のfulltime平均値を使ってどのように表せるでしょうか?

## 回帰式

$$
Y_{i} = \beta_{0}+\beta_{1} \text{state}_{i}+\beta_{2} \text{time}_{i}+ \beta_{3}(\text{state}_{i} \times \text{time}_{i})+\epsilon_{i}
$$

$Y_{i}$ : fulltime. フルタイム換算の雇用者数。

### 固定効果推定

```{stata}
xtreg fulltime time timestate, fe vce(cluster store)
```

`vce(cluster store)`: store(店舗id)をクラスターと考え、クラスター頑健誤差を使用。 

#### 練習問題6: 回帰係数の推定値を使うとニュージャージー州による最低賃金引き上げの政策効果はどのように表せるでしょうか?

### クラスター頑健誤差（Cluster-Robust Standard Errors）

#### 復習：OLSにおける誤差に関する仮定

参考文献: 教科書(藪友良『入門 実践する計量経済学』、2023年、東洋経済新報社)のp.52 「3.2 回帰分析における標準的仮定」。

回帰モデルを次のように書きます：

$$
Y_{i} = \beta_{0} + \beta_{1} X_{i} + e_{i}
$$

通常、OLSによる推定では誤差 $e_{i}$ について、暗黙に次のことを仮定しています。

- 仮定A (独立性): $i \neq j$ であれば $e_{i}$ と $e_{j}$ は独立である。
- 仮定B (均一分散): すべての $i$ において誤差 $e_{i}$ の分散の大きさは $\sigma^2$ で一定である。

#### 仮定Aと仮定Bの重要性

t検定やp値を使った統計的仮説検定を正しく行うためには推定値の取り得る範囲（標準誤差）をより正確に得ることが重要であり、そのために上で述べた 仮定A（独立性） と 仮定B（均一分散） の2つの仮定を満たすことは極めて重要です。

$\beta_{1}$ のOLS 推定量は $\bar{X}, \bar{Y}$ をそれぞれ $X, Y$ の平均として

$$
\hat{\beta}_{1} = \frac{\sum_{i} (X_{i}-\bar{X})(Y_{i}-\bar{Y})}{\sum_{i}(X_{i}-\bar{X})^{2}}
$$

と与えられます。

$$
\hat{\beta}_{1} = \beta_{1}+\frac{\sum_{i} (X_{i}-\bar{X})e_{i}}{\sum_{i}(X_{i}-\bar{X})^{2}}
$$

より、もし仮定Aと仮定Bが成立しているならば $\hat{\beta}_{1}$ の分散は

$$
\text{Var}(\hat{\beta}_{1}) = \frac{\sigma^{2}}{\sum_{i}(X_{i}-\bar{X})^{2}}
$$ {#eq-black-scholes}

と書けます。

#### White 頑健標準誤差（Heteroskedasticity-Robust Standard Errors）

参考文献: 教科書(藪友良『入門 実践する計量経済学』、2023年、東洋経済新報社)の第9章 「不均一分散」および経済統計学第7講講義資料。

経済統計学第7講(2025年12月2日)で行った質的選択モデルの推定では推定値の取り得る範囲（標準誤差）をより正確に得るために「頑健な推定値の標準誤差（Stataの`robust`コマンド）」を使いました。

なぜなら実際のデータにおいては仮定Bの均一分散 (homoscedasticity) の仮定は実際には満たされていない場合が多いからです。

もし実際には $i$ ごとに分散が異なり、$\sigma_{i}$ となっている場合、上の @eq-black-scholes は正しくなく、誤った値 を与えてしまいます。それに対処するためにWhite 頑健標準誤差（Heteroskedasticity-Robust Standard Errors）が一般に用いられます。そのアイデアは「均一分散を仮定せずに、観測ごとに異なる分散 $\sigma_i^2$ を許したまま、$\hat{\beta}$ の分散を推定し直す」というものです。

しかし、実際のデータにおいては多くの観測値は自然なグループ（クラスター）に分かれていることが指摘されています。例えば、複数の学校の生徒の成績データなら同じ学校というグループ、労働者に関するデータなら同じ企業や同じ職種というグループ、地域のデータなら同じ県・市町村というグループが考えられます。このとき、同じクラスター内の誤差は似た動きをする可能性があります。つまり、仮定Aが破れてしまう可能性が出てきます。それに対処するためのものが **クラスター頑健標準誤差（Cluster-Robust Standard Errors）**　です。

#### クラスター頑健標準誤差（Cluster-Robust Standard Errors）

参考文献

- ヨシュア・アングリスト, ヨーン・シュテファン・ピスケ 著ほか. 「ほとんど無害」な計量経済学 : 応用経済学のための実証分析ガイド, NTT出版, 2013年.
- 川口康平, 澤田真行 著. 因果推論の計量経済学, 日本評論社, 2024.

**クラスター内相関とは何か**

たとえば簡単な例として学校とテスト点数の関係性について考えます。学校Aにタブレットなどの設備を導入する処置が行われたとして、それが生徒のテスト成績を上げたのかどうかを調べたいとします。ここで考えなければいけないのは、処置の有無以外にも同じ学校の生徒は、共通の見えない要因を共有する可能性があることです。例えば処置が行われた学校Aと行われなかった学校Bではもともと学校Aのほうが教育熱心な先生が多かったかもしれません。このとき、$g$ を学校Aに所属しているのか、Bに所属しているのかを表すインデックスとすると($i$ は生徒のインデックスです)、誤差項 $e_{ig}$ は

$$
e_{ig} = \text{学校gに共通の要因}+\text{個人iに特有の要因}
$$

と分解できるはずです。すると、もちろん個人に特有な要因の部分はそれぞれで異なると考えられますが、同じ学校内では前者の「学校gに共通の要因」は相関を持つ可能性があります。

問題点は通常、「データが100個あれば、独立な情報が100個ある」と解釈することができますが、もし同じ学校内で誤差が相関していると、たとえば学校が10校しかなければ、100/10=10で、実質的な独立情報は10個分しかないことになってしまいます。これにより標準誤差が過小評価され、t値が過大評価され、有意でないものを有意と誤って判定してしまうリスクがあります。

そこで、クラスター頑健誤差は、次のルールを採用します。

1. 異なるクラスター間では独立
2. 同じクラスター内では自由に相関してよい

先ほどの例でいえば、学校AとBの間では独立、学校Aの生徒同士は、どれだけ相関してもOKというルールです。

| 推定法         | 許すもの             | 許さないもの   |
| ----------- | ---------------- | -------- |
| 通常OLS       | 同分散・独立           | 不均一・相関   |
| White       | 不均一分散            | 相関       |
| **クラスター** | 不均一分散＋相関（クラスター内） | クラスター間相関 |

クラスター頑健標準誤差において重要なのは「クラスター数 g」をどう設定するか、ということになります。観測数が多いから大丈夫なわけでもなく、クラスター数が少ないともちろんですがその近似が悪くなってしまいます。基本的には「誤差が相関しそうな最も粗い単位」にクラスターを設定することが多いです。「処置がどこで割り当てられたか」をヒントに設定することが多いです。

## 追加コントロールを入れた固定効果推定

```{stata}
xtreg fulltime time timestate hours register, fe vce(cluster store)
```

# おわりに

ここまででみなさんはノーベル経済学賞の受賞理由の一つとなった論文を再現することができました。元の論文を読んでみて内容が理解できるか確かめてみると楽しいかもしれません。
