---
title: "政策評価モデルに関する講義用データファイル"
date: today
date-format: "YYYY年M月D日"
author:
  - name: "福井裕貴"
    email: "227e127e@gsuite.kobe-u.ac.jp"
    affiliations:
      - name: "K神戸大学大学大学院経済学研究科博士後期課程"
execute: 
  echo: false
  warning: false
  message: false
format: typst
engine: jupyter
brand:
  typography:      
    fonts:
      - family: Noto Serif JP
        source: google
      - family: IBM Plex Sans JP
        source: google
    base: Noto Serif JP
    headings:
      family: IBM Plex Sans JP
      weight: regular
number-sections: true
---

# はじめに


#　政策評価における因果推論の枠組み

# DiD

```{r}
install.packages("causaldata")
library(causaldata)
data("castle")
```

